services:
  Ardiakov\StringStackCalcBundle\Services\CountManager:
    autowire: true

  Ardiakov\StringStackCalcBundle\Services\Counter\SimpleCalculator:
    autowire: true

  Ardiakov\StringStackCalcBundle\Services\Counter\CounterServiceInterface: '@Ardiakov\StringStackCalcBundle\Services\Counter\SimpleCalculator'


